# Revised Versions
## Zhonghe Han 00001425699
## Redesign
### Finding 1
### Improvement
In first version graph I showed trend of sum number records for mass gun shooting from 2014 to 2018. From the chart we can see it told mass gun shooting in America arrived its peak in 2016 and then fall down in 2017 and different from view 'mass shooting increasing after 2012' presented by original data product.

However this trend is different from common sense and frequent mass shooting make us feel terrorist never reduce their willing to shoot. Is people really decreased willing of using guns or there is other reason? From some essays I found reason for decreasing gun shooting in 2017. Since new policy make fears of tighter controls to buy guns fade, people tend not buy guns rushly and gun sales decline in 2017. We may say less gun selling lead to decrease of mass gun shooting though people didn't do this consciously. There maybe other reasons but this one can explain part of decreasing. From chart below we can see relation between gun selling and mass shooting. I use data of number for background checking when buy guns as y axis and year as x axis.
### Polishing
Last time this graph is already quite satisfying so I decide to find more explaination for the chart which only shows a fact. Following GQM model, I tried to find goal of my data product. The goal should be showing how serious gun problem is and America should decrease gun amounts, in other words my charts should make people feel it is necessary to control guns. Question rise from my chart then become what is true reason of mass shooting decreasing, reaon that can support my goal. Finally from essays I found president Trump's friendly-gun attitude can be used here, so metric become background checking when buy guns. With this reason, my chart shows it is decreasing of buying gun make mass gun shooting decrease therefore it is necessary to control guns.

### Finding 2
### Improvement
From first version chart I drew, I tried to show relation between firearms number and homicide by firearm. But due to included all countries and didn't sort any variable, the chart seems confused and disordered. We cannot tell how America perform compare to other countries. 
In revising chart, I choose to draw these two variables in two different charts and both as y axis with same countries name as x axis. In this way it is easier for audience to see gun amount and homicide by firearm among countries. Also I only use developed countries instead all countries, for I think America is a developed country also can make chart more clear. From this chart, we can see average firearms per 100 people in America is twice than the second country and its number is around 90, which means on average in 100 American 90 of them have gun. Also, number of homicide by firearm per 100k people in America is top one and almost four times than second country. This actually prove original data product's claim, more guns in lead to high homicide by firearm but more clear than original one, which only shows number of homicide by firearm. 
Still finding 2 enhance conclusion of finding 1, more guns do lead to more gun related events. 
### Polishing
Finding 2 is based on chart 1 in original data prodcut. When thinking how to improve it, I followed the audience model. For conclusion of chart 1 in original data product, it said more firearm homicides in America is because it has way more guns than other developed nations, I thought this as what audience 'want'. According to this, I think audience 'need' metrics such as guns amount in all developed countries. Also I should avoid what audience 'fear', that would be including other developing countries in chart, because as we known some developing countries are war countries and their data will make America no longer an outlier. Thus, I only include developed countries and found firearms owned number. 

### Finding 3
### Improvement
From first version chart, I tried to explain relation between gun related laws and firearm death rate. However in first version, I piled up states with same numer gun related laws together in one same bar, which was a bad way to show relation and easily became a misleading chart. For instance, in that chart it seems states with one law term tend to have more firearm death than states without any law (which is not true), for number of states with one law is more than number of states without law.
In my revising verison, I seperated states into three groups, states without law, states with one law and states with two more laws. Then instead piling up all states to one bar, using states name as x axis, firearm death rate per 100k people as y axis, I drew three charts for each group and showed average death number on chart. In this way, we can see relation between gun related laws and gun death easily. States without any gun laws average gun death is 15.53, in states with one law it decline to 13.79 and in states with two more laws it lower to 6.68. Therefore we may safely say more gun related laws lead to less gun related death. Also I drew a general chart include all states to show this relation by color. We can see from second chart, the deeper the color the more states have gun laws. And similarly, we see states with more laws tend to lower their firearm death number.  
Again finding 3 enhance previous two findings, by controlling guns America will have less gun death.
### Polishing
When making this chart I was confused by original data product as well as my first version. For somehow my charts contradicted with claim. After applied argumentation model, I built a connection between my data and claim. Base on dataset I had, which shows clear relation of states with two or more laws have lower gun death, I set up a claim that more guns laws lead to lower gun death. When checking whether my product is qualifier or not, I used average line of gun death for states in different laws level. And as displayed in chart above, since chart showed states with more gun laws have less gun death, it support my claim well. Also more gun laws leading to less gun death is a common sense which fit to my understanding, this is a good backing. 